### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by bbjubjub2494** [nix-community/nur-packages-template#94] opened 2024-06-04 07:47 UTC
The Github actions now fail with

```
warning: Nix search path entry 'channel:nixpkgs-unstable' cannot be downloaded, ignoring
error:
       … while calling the 'import' builtin
         at «string»:1:2:
            1| (import <nixpkgs> {}).lib.version
             |  ^

       … while realising the context of a path

       … while calling the 'findFile' builtin
         at «string»:1:9:
            1| (import <nixpkgs> {}).lib.version
             |         ^

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

Here is a fresh repository showing the issue: https://github.com/bbjubjub2494/nur_template_test/actions/runs/9363137315/job/25773257833

We have scheduled builds and they stopped failing 3 days ago with no commit on our side: https://github.com/Red-Flake/packages/actions. The version of nix is 2.22.1 in both cases. Something changed in the ambient inputs but I have no idea what.

**Comment by Mic92** [comment] 2024-06-04 08:42
I noticed that as well. I cannot reproduce it locally though `nix-shell -I nixpkgs=channel:nixos-unstable -p hello` with the same nix version.

**Comment by Mic92** [comment] 2024-06-04 08:46
fixed in https://github.com/nix-community/nur-packages-template/pull/95

**Closed by Mic92** 2024-06-04 08:46 UTC
